### ISSUE TITLE
Cannot find module 'nioa-protocol'

### ISSUE THREAD

**Issue by sabelosimelane** [noia-network/noia-node-terminal#2]
I am getting the error "cannot find module 'noia-protocol'". Am I missing something?

No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.4 LTS
Release:        16.04
Codename:       xenial
npm --version: 6.1.0
nodejs --version: v10.5.0

![image](https://user-images.githubusercontent.com/1929271/41737067-7e0aaa20-758e-11e8-9f1f-dcb33deb8c46.png)

**Comment by MartynasZilinskas** [comment]
Hey @sabelosimelane. This issue should be fixed by now. You can re-download the latest [archive here](https://github.com/noia-network/noia-node-terminal/archive/master.zip).

Tested on Windows 10.

**Comment by sabelosimelane** [comment]
Hi now, it's complaining about the noia-node

![image](https://user-images.githubusercontent.com/1929271/41784247-6bc5b1a0-763f-11e8-85e8-aa9f10d56ef1.png)

**Comment by MartynasZilinskas** [comment]
This issue should be resolved with [v0.1.2](https://github.com/noia-network/noia-node-terminal/archive/v0.1.2.zip).

Tested on Ubuntu 16.04.4 LTS

**Comment by sabelosimelane** [comment]
I tested, it's working. Thank you very much.
